[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.14.3"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[override]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"
